ergo
JonathanLorimer/weft pull request #70
Opened 2019-08-08 16:40 UTC by isovector

2019-08-17 20:05 UTC, JonathanLorimer requested changes
left a couple comments

2019-08-17 20:05 UTC, JonathanLorimer commented on src/Weft/Generics/AllTypes.hs
> +  --( HasAllTypes
Do we still need this?

2019-08-17 20:05 UTC, JonathanLorimer commented on src/Weft/Generics/Hydrate.hs
> +  -- , hydrateF
Can we add hydrateF back?

2019-08-17 20:05 UTC, JonathanLorimer commented on src/Weft/Generics/Hydrate.hs
> +magicHydrate :: HasMagicHydrate record => record -> JHKD record 'Query -> JHKD record 'Response
can we just call it hydrate?

2019-08-17 20:05 UTC, JonathanLorimer commented on src/Weft/Generics/Hydrate.hs
> +-- instance (Generic record, GHydrate (Rep record)
can this be removed?

2019-08-17 20:05 UTC, JonathanLorimer commented on src/Weft/Generics/JSONResponse.hs
> +  , magicJsonResponse
Isn't the user going use this function? shouldn't it be called `jsonResponse`

2019-08-17 20:05 UTC, JonathanLorimer commented on src/Weft/Generics/QueryParser.hs
> +  -- , anonymousQueryParser
Can we get rid of this?

2019-08-17 20:05 UTC, JonathanLorimer commented on src/Weft/Generics/QueryParser.hs
> +-- anonymousQueryParser :: HasQueryParser q => ReaderT Vars Parser (Gql q m s 'Query)
Same with this

2019-08-17 20:05 UTC, JonathanLorimer commented on test/AllTypesSpec.hs
>  module AllTypesSpec where
should delete this too

2019-08-18 01:53 UTC, isovector commented on src/Weft/Generics/Hydrate.hs
> +magicHydrate :: HasMagicHydrate record => record -> JHKD record 'Query -> JHKD record 'Response
yes but later!

2019-08-18 01:53 UTC, isovector commented on src/Weft/Generics/JSONResponse.hs
> +  , magicJsonResponse
yes but later

2019-08-18 01:53 UTC, isovector commented on src/Weft/Generics/QueryParser.hs
> +  -- , anonymousQueryParser
this still needs to exist! let me rewrite it

2019-08-18 01:59 UTC, JonathanLorimer approved these changes

2019-08-18 02:07 UTC, merged